apiVersion: v1
kind: ConfigMap
metadata:
  name: users-config
  namespace: agrosolutions
  labels:
    app: users-api
    component: backend
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
